/* AX Engine — llama.cpp C API compatibility header
 *
 * Auto-generated by cbindgen from Rust source. Do not edit manually.
 * Provides the same function signatures as llama.cpp's llama.h
 * for drop-in binary compatibility on Apple Silicon M3+.
 */

#ifndef LLAMA_H
#define LLAMA_H

#include <stdbool.h>
#include <stdint.h>

/**
 * Opaque context handle.
 * Owns inference state: KV cache, logits buffer, position, and RNG.
 */
typedef struct llama_context llama_context;

/**
 * Opaque model handle.
 * Owns the GGUF mmap, config, tokenizer, and forward-pass model.
 */
typedef struct llama_model llama_model;

/**
 * Model loading parameters.
 */
typedef struct {
  int n_gpu_layers;
  bool use_mmap;
  bool use_mlock;
} llama_model_params;

/**
 * Context creation parameters.
 */
typedef struct {
  uint32_t n_ctx;
  uint32_t n_batch;
  uint32_t n_threads;
  uint32_t n_threads_batch;
  uint32_t seed;
} llama_context_params;

/**
 * Token type alias (matches llama.h: typedef int32_t llama_token).
 */
typedef int32_t llama_token;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the AX Engine backend. Must be called before any other function.
 */
void llama_backend_init(void);

/**
 * Free the AX Engine backend resources.
 */
void llama_backend_free(void);

/**
 * Return default model params.
 */
llama_model_params llama_model_default_params(void);

/**
 * Return default context params.
 */
llama_context_params llama_context_default_params(void);

/**
 * Create a new inference context from a loaded model.
 *
 * Returns null on failure.
 */
llama_context *llama_new_context_with_model(llama_model *model, llama_context_params params);

/**
 * Free an inference context.
 */
void llama_free(llama_context *ctx);

/**
 * Get context size.
 */
int32_t llama_n_ctx(const llama_context *ctx);

/**
 * Clear the KV cache (reset for new conversation).
 */
void llama_kv_cache_clear(llama_context *ctx);

/**
 * Run the forward pass (evaluate tokens).
 *
 * Processes `n_tokens` tokens starting at position `n_past` in the context.
 * Returns 0 on success, negative on error.
 */
int32_t llama_eval(llama_context *ctx, const llama_token *tokens, int32_t n_tokens, int32_t n_past);

/**
 * Get logits output from the last eval.
 *
 * Returns pointer to float array of size n_vocab.
 * The pointer is valid until the next call to llama_eval or llama_free.
 */
float *llama_get_logits(llama_context *ctx);

/**
 * Load a GGUF model from file.
 *
 * Returns null on failure.
 */
llama_model *llama_model_load_from_file(const char *path, llama_model_params _params);

/**
 * Free a loaded model.
 */
void llama_free_model(llama_model *model);

/**
 * Get vocabulary size.
 */
int32_t llama_n_vocab(const llama_model *model);

/**
 * Get number of layers.
 */
int32_t llama_n_layer(const llama_model *model);

/**
 * Get embedding dimension.
 */
int32_t llama_n_embd(const llama_model *model);

/**
 * Get BOS token ID.
 */
llama_token llama_token_bos(const llama_model *model);

/**
 * Get EOS token ID.
 */
llama_token llama_token_eos(const llama_model *model);

/**
 * Apply temperature scaling to logits.
 */
void llama_sample_temperature(llama_context *_ctx, float *logits, int32_t n_vocab, float temp);

/**
 * Apply top-k filtering to logits.
 */
void llama_sample_top_k(llama_context *_ctx, float *logits, int32_t n_vocab, int32_t k);

/**
 * Apply top-p (nucleus) filtering to logits.
 */
void llama_sample_top_p(llama_context *_ctx, float *logits, int32_t n_vocab, float p);

/**
 * Apply repetition penalty to logits.
 */
void llama_sample_repetition_penalty(llama_context *_ctx,
                                     float *logits,
                                     int32_t n_vocab,
                                     const llama_token *last_tokens,
                                     int32_t last_n,
                                     float penalty);

/**
 * Greedy sampling: return the token with the highest logit.
 */
llama_token llama_sample_token_greedy(llama_context *_ctx, const float *logits, int32_t n_vocab);

/**
 * Sample a token from logits using softmax + weighted random selection.
 *
 * Call this after applying temperature, top-k, top-p, etc.
 * Uses the context's RNG state for reproducibility.
 */
llama_token llama_sample_token(llama_context *ctx, float *logits, int32_t n_vocab);

/**
 * Tokenize text into token IDs.
 *
 * Returns the number of tokens written.
 * If `tokens` is null, returns the number of tokens that would be produced.
 * Returns negative (-n_needed) if the output buffer is too small.
 */
int32_t llama_tokenize(const llama_model *model,
                       const char *text,
                       int32_t text_len,
                       llama_token *tokens,
                       int32_t n_tokens_max,
                       bool add_special,
                       bool _parse_special);

/**
 * Convert a token ID to text.
 *
 * Returns the number of bytes written. Returns negative if buffer too small.
 */
int32_t llama_token_to_piece(const llama_model *model,
                             llama_token token,
                             char *buf,
                             int32_t length,
                             int32_t _lstrip,
                             bool _special);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LLAMA_H */
