// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ax_engine.proto

package ax_engine_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_ax_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_ax_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type ModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsRequest) Reset() {
	*x = ModelsRequest{}
	mi := &file_ax_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsRequest) ProtoMessage() {}

func (x *ModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsRequest.ProtoReflect.Descriptor instead.
func (*ModelsRequest) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{2}
}

type ModelCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	OwnedBy       string                 `protobuf:"bytes,3,opt,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCard) Reset() {
	*x = ModelCard{}
	mi := &file_ax_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCard) ProtoMessage() {}

func (x *ModelCard) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCard.ProtoReflect.Descriptor instead.
func (*ModelCard) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ModelCard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelCard) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ModelCard) GetOwnedBy() string {
	if x != nil {
		return x.OwnedBy
	}
	return ""
}

type ModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Data          []*ModelCard           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsResponse) Reset() {
	*x = ModelsResponse{}
	mi := &file_ax_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsResponse) ProtoMessage() {}

func (x *ModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsResponse.ProtoReflect.Descriptor instead.
func (*ModelsResponse) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{4}
}

func (x *ModelsResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ModelsResponse) GetData() []*ModelCard {
	if x != nil {
		return x.Data
	}
	return nil
}

type GenerateSampling struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Temperature       float32                `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP              float32                `protobuf:"fixed32,2,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	TopK              uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	RepetitionPenalty float32                `protobuf:"fixed32,4,opt,name=repetition_penalty,json=repetitionPenalty,proto3" json:"repetition_penalty,omitempty"`
	Seed              uint64                 `protobuf:"varint,5,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateSampling) Reset() {
	*x = GenerateSampling{}
	mi := &file_ax_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSampling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSampling) ProtoMessage() {}

func (x *GenerateSampling) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSampling.ProtoReflect.Descriptor instead.
func (*GenerateSampling) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateSampling) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateSampling) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *GenerateSampling) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *GenerateSampling) GetRepetitionPenalty() float32 {
	if x != nil {
		return x.RepetitionPenalty
	}
	return 0
}

func (x *GenerateSampling) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type GenerateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Model           string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	InputTokens     []uint32               `protobuf:"varint,2,rep,packed,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	InputText       string                 `protobuf:"bytes,3,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	MaxOutputTokens uint32                 `protobuf:"varint,4,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	Sampling        *GenerateSampling      `protobuf:"bytes,5,opt,name=sampling,proto3" json:"sampling,omitempty"`
	Metadata        string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_ax_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateRequest) GetInputTokens() []uint32 {
	if x != nil {
		return x.InputTokens
	}
	return nil
}

func (x *GenerateRequest) GetInputText() string {
	if x != nil {
		return x.InputText
	}
	return ""
}

func (x *GenerateRequest) GetMaxOutputTokens() uint32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *GenerateRequest) GetSampling() *GenerateSampling {
	if x != nil {
		return x.Sampling
	}
	return nil
}

func (x *GenerateRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	PromptTokens  []uint32               `protobuf:"varint,3,rep,packed,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	OutputTokens  []uint32               `protobuf:"varint,4,rep,packed,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	OutputText    string                 `protobuf:"bytes,5,opt,name=output_text,json=outputText,proto3" json:"output_text,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	FinishReason  string                 `protobuf:"bytes,7,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	StepCount     uint64                 `protobuf:"varint,8,opt,name=step_count,json=stepCount,proto3" json:"step_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_ax_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *GenerateResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GenerateResponse) GetPromptTokens() []uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return nil
}

func (x *GenerateResponse) GetOutputTokens() []uint32 {
	if x != nil {
		return x.OutputTokens
	}
	return nil
}

func (x *GenerateResponse) GetOutputText() string {
	if x != nil {
		return x.OutputText
	}
	return ""
}

func (x *GenerateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *GenerateResponse) GetStepCount() uint64 {
	if x != nil {
		return x.StepCount
	}
	return 0
}

type RequestReport struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestId             uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ModelId               string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	State                 string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	PromptTokens          []uint32               `protobuf:"varint,4,rep,packed,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	ProcessedPromptTokens uint32                 `protobuf:"varint,5,opt,name=processed_prompt_tokens,json=processedPromptTokens,proto3" json:"processed_prompt_tokens,omitempty"`
	OutputTokens          []uint32               `protobuf:"varint,6,rep,packed,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	PromptLen             uint32                 `protobuf:"varint,7,opt,name=prompt_len,json=promptLen,proto3" json:"prompt_len,omitempty"`
	OutputLen             uint32                 `protobuf:"varint,8,opt,name=output_len,json=outputLen,proto3" json:"output_len,omitempty"`
	MaxOutputTokens       uint32                 `protobuf:"varint,9,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	CancelRequested       bool                   `protobuf:"varint,10,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RequestReport) Reset() {
	*x = RequestReport{}
	mi := &file_ax_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReport) ProtoMessage() {}

func (x *RequestReport) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReport.ProtoReflect.Descriptor instead.
func (*RequestReport) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{8}
}

func (x *RequestReport) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RequestReport) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RequestReport) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RequestReport) GetPromptTokens() []uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return nil
}

func (x *RequestReport) GetProcessedPromptTokens() uint32 {
	if x != nil {
		return x.ProcessedPromptTokens
	}
	return 0
}

func (x *RequestReport) GetOutputTokens() []uint32 {
	if x != nil {
		return x.OutputTokens
	}
	return nil
}

func (x *RequestReport) GetPromptLen() uint32 {
	if x != nil {
		return x.PromptLen
	}
	return 0
}

func (x *RequestReport) GetOutputLen() uint32 {
	if x != nil {
		return x.OutputLen
	}
	return 0
}

func (x *RequestReport) GetMaxOutputTokens() uint32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *RequestReport) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

type StepReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ScheduledRequests uint32                 `protobuf:"varint,1,opt,name=scheduled_requests,json=scheduledRequests,proto3" json:"scheduled_requests,omitempty"`
	ScheduledTokens   uint32                 `protobuf:"varint,2,opt,name=scheduled_tokens,json=scheduledTokens,proto3" json:"scheduled_tokens,omitempty"`
	TtftEvents        uint32                 `protobuf:"varint,3,opt,name=ttft_events,json=ttftEvents,proto3" json:"ttft_events,omitempty"`
	PrefixHits        uint32                 `protobuf:"varint,4,opt,name=prefix_hits,json=prefixHits,proto3" json:"prefix_hits,omitempty"`
	KvUsageBlocks     uint32                 `protobuf:"varint,5,opt,name=kv_usage_blocks,json=kvUsageBlocks,proto3" json:"kv_usage_blocks,omitempty"`
	Evictions         uint32                 `protobuf:"varint,6,opt,name=evictions,proto3" json:"evictions,omitempty"`
	CpuTimeUs         uint64                 `protobuf:"varint,7,opt,name=cpu_time_us,json=cpuTimeUs,proto3" json:"cpu_time_us,omitempty"`
	RunnerTimeUs      uint64                 `protobuf:"varint,8,opt,name=runner_time_us,json=runnerTimeUs,proto3" json:"runner_time_us,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StepReport) Reset() {
	*x = StepReport{}
	mi := &file_ax_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepReport) ProtoMessage() {}

func (x *StepReport) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepReport.ProtoReflect.Descriptor instead.
func (*StepReport) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{9}
}

func (x *StepReport) GetScheduledRequests() uint32 {
	if x != nil {
		return x.ScheduledRequests
	}
	return 0
}

func (x *StepReport) GetScheduledTokens() uint32 {
	if x != nil {
		return x.ScheduledTokens
	}
	return 0
}

func (x *StepReport) GetTtftEvents() uint32 {
	if x != nil {
		return x.TtftEvents
	}
	return 0
}

func (x *StepReport) GetPrefixHits() uint32 {
	if x != nil {
		return x.PrefixHits
	}
	return 0
}

func (x *StepReport) GetKvUsageBlocks() uint32 {
	if x != nil {
		return x.KvUsageBlocks
	}
	return 0
}

func (x *StepReport) GetEvictions() uint32 {
	if x != nil {
		return x.Evictions
	}
	return 0
}

func (x *StepReport) GetCpuTimeUs() uint64 {
	if x != nil {
		return x.CpuTimeUs
	}
	return 0
}

func (x *StepReport) GetRunnerTimeUs() uint64 {
	if x != nil {
		return x.RunnerTimeUs
	}
	return 0
}

type GenerateStepEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *RequestReport         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Step          *StepReport            `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	DeltaTokens   []uint32               `protobuf:"varint,3,rep,packed,name=delta_tokens,json=deltaTokens,proto3" json:"delta_tokens,omitempty"`
	DeltaText     string                 `protobuf:"bytes,4,opt,name=delta_text,json=deltaText,proto3" json:"delta_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateStepEvent) Reset() {
	*x = GenerateStepEvent{}
	mi := &file_ax_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStepEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStepEvent) ProtoMessage() {}

func (x *GenerateStepEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStepEvent.ProtoReflect.Descriptor instead.
func (*GenerateStepEvent) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateStepEvent) GetRequest() *RequestReport {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GenerateStepEvent) GetStep() *StepReport {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *GenerateStepEvent) GetDeltaTokens() []uint32 {
	if x != nil {
		return x.DeltaTokens
	}
	return nil
}

func (x *GenerateStepEvent) GetDeltaText() string {
	if x != nil {
		return x.DeltaText
	}
	return ""
}

type GenerateStreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event name: "request" | "step" | "response"
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// exactly one of the following is set based on event
	Request       *RequestReport     `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Step          *GenerateStepEvent `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	Response      *GenerateResponse  `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateStreamEvent) Reset() {
	*x = GenerateStreamEvent{}
	mi := &file_ax_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStreamEvent) ProtoMessage() {}

func (x *GenerateStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStreamEvent.ProtoReflect.Descriptor instead.
func (*GenerateStreamEvent) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateStreamEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *GenerateStreamEvent) GetRequest() *RequestReport {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GenerateStreamEvent) GetStep() *GenerateStepEvent {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *GenerateStreamEvent) GetResponse() *GenerateResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_ax_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{12}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatCompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Seed          uint64                 `protobuf:"varint,5,opt,name=seed,proto3" json:"seed,omitempty"`
	Stop          []string               `protobuf:"bytes,6,rep,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_ax_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{13}
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatCompletionRequest) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ChatCompletionRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     uint32                 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32                 `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      uint32                 `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_ax_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{14}
}

func (x *TokenUsage) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ChatCompletionChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Message       *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionChoice) Reset() {
	*x = ChatCompletionChoice{}
	mi := &file_ax_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChoice) ProtoMessage() {}

func (x *ChatCompletionChoice) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChoice.ProtoReflect.Descriptor instead.
func (*ChatCompletionChoice) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{15}
}

func (x *ChatCompletionChoice) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletionChoice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatCompletionChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ChatCompletionResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                  `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                  `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*ChatCompletionChoice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage         *TokenUsage             `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_ax_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{16}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetChoices() []*ChatCompletionChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ChatDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatDelta) Reset() {
	*x = ChatDelta{}
	mi := &file_ax_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDelta) ProtoMessage() {}

func (x *ChatDelta) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDelta.ProtoReflect.Descriptor instead.
func (*ChatDelta) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{17}
}

func (x *ChatDelta) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatDelta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatCompletionChunkChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Delta         *ChatDelta             `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionChunkChoice) Reset() {
	*x = ChatCompletionChunkChoice{}
	mi := &file_ax_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChunkChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunkChoice) ProtoMessage() {}

func (x *ChatCompletionChunkChoice) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunkChoice.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunkChoice) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{18}
}

func (x *ChatCompletionChunkChoice) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletionChunkChoice) GetDelta() *ChatDelta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *ChatCompletionChunkChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type ChatCompletionChunk struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Id            string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                       `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                        `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                       `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*ChatCompletionChunkChoice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionChunk) Reset() {
	*x = ChatCompletionChunk{}
	mi := &file_ax_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk) ProtoMessage() {}

func (x *ChatCompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{19}
}

func (x *ChatCompletionChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionChunk) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionChunk) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionChunk) GetChoices() []*ChatCompletionChunkChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

type CompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Seed          uint64                 `protobuf:"varint,5,opt,name=seed,proto3" json:"seed,omitempty"`
	Stop          []string               `protobuf:"bytes,6,rep,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_ax_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{20}
}

func (x *CompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CompletionRequest) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompletionRequest) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *CompletionRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

type CompletionChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionChoice) Reset() {
	*x = CompletionChoice{}
	mi := &file_ax_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionChoice) ProtoMessage() {}

func (x *CompletionChoice) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionChoice.ProtoReflect.Descriptor instead.
func (*CompletionChoice) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{21}
}

func (x *CompletionChoice) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CompletionChoice) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CompletionChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type CompletionChunkChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	FinishReason  string                 `protobuf:"bytes,3,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionChunkChoice) Reset() {
	*x = CompletionChunkChoice{}
	mi := &file_ax_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionChunkChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionChunkChoice) ProtoMessage() {}

func (x *CompletionChunkChoice) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionChunkChoice.ProtoReflect.Descriptor instead.
func (*CompletionChunkChoice) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{22}
}

func (x *CompletionChunkChoice) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CompletionChunkChoice) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CompletionChunkChoice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

type CompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*CompletionChoice    `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_ax_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{23}
}

func (x *CompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompletionResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *CompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *CompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionResponse) GetChoices() []*CompletionChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *CompletionResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type CompletionChunk struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                   `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                   `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*CompletionChunkChoice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionChunk) Reset() {
	*x = CompletionChunk{}
	mi := &file_ax_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionChunk) ProtoMessage() {}

func (x *CompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionChunk.ProtoReflect.Descriptor instead.
func (*CompletionChunk) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{24}
}

func (x *CompletionChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompletionChunk) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *CompletionChunk) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *CompletionChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionChunk) GetChoices() []*CompletionChunkChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

type EmbeddingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Input         []uint32               `protobuf:"varint,2,rep,packed,name=input,proto3" json:"input,omitempty"`
	Pooling       string                 `protobuf:"bytes,3,opt,name=pooling,proto3" json:"pooling,omitempty"`
	Normalize     bool                   `protobuf:"varint,4,opt,name=normalize,proto3" json:"normalize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingsRequest) Reset() {
	*x = EmbeddingsRequest{}
	mi := &file_ax_engine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingsRequest) ProtoMessage() {}

func (x *EmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{25}
}

func (x *EmbeddingsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingsRequest) GetInput() []uint32 {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *EmbeddingsRequest) GetPooling() string {
	if x != nil {
		return x.Pooling
	}
	return ""
}

func (x *EmbeddingsRequest) GetNormalize() bool {
	if x != nil {
		return x.Normalize
	}
	return false
}

type EmbeddingData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Index         uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingData) Reset() {
	*x = EmbeddingData{}
	mi := &file_ax_engine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingData) ProtoMessage() {}

func (x *EmbeddingData) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingData.ProtoReflect.Descriptor instead.
func (*EmbeddingData) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{26}
}

func (x *EmbeddingData) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *EmbeddingData) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbeddingData) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type EmbeddingUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens  uint32                 `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	TotalTokens   uint32                 `protobuf:"varint,2,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingUsage) Reset() {
	*x = EmbeddingUsage{}
	mi := &file_ax_engine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingUsage) ProtoMessage() {}

func (x *EmbeddingUsage) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingUsage.ProtoReflect.Descriptor instead.
func (*EmbeddingUsage) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{27}
}

func (x *EmbeddingUsage) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *EmbeddingUsage) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type EmbeddingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Data          []*EmbeddingData       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Usage         *EmbeddingUsage        `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingsResponse) Reset() {
	*x = EmbeddingsResponse{}
	mi := &file_ax_engine_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingsResponse) ProtoMessage() {}

func (x *EmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ax_engine_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_ax_engine_proto_rawDescGZIP(), []int{28}
}

func (x *EmbeddingsResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *EmbeddingsResponse) GetData() []*EmbeddingData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EmbeddingsResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingsResponse) GetUsage() *EmbeddingUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

var File_ax_engine_proto protoreflect.FileDescriptor

const file_ax_engine_proto_rawDesc = "" +
	"\n" +
	"\x0fax_engine.proto\x12\fax_engine.v1\"\x0f\n" +
	"\rHealthRequest\"]\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\"\x0f\n" +
	"\rModelsRequest\"N\n" +
	"\tModelCard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x19\n" +
	"\bowned_by\x18\x03 \x01(\tR\aownedBy\"U\n" +
	"\x0eModelsResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12+\n" +
	"\x04data\x18\x02 \x03(\v2\x17.ax_engine.v1.ModelCardR\x04data\"\xa1\x01\n" +
	"\x10GenerateSampling\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\x02 \x01(\x02R\x04topP\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x12-\n" +
	"\x12repetition_penalty\x18\x04 \x01(\x02R\x11repetitionPenalty\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\x04R\x04seed\"\xed\x01\n" +
	"\x0fGenerateRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\x02 \x03(\rR\vinputTokens\x12\x1d\n" +
	"\n" +
	"input_text\x18\x03 \x01(\tR\tinputText\x12*\n" +
	"\x11max_output_tokens\x18\x04 \x01(\rR\x0fmaxOutputTokens\x12:\n" +
	"\bsampling\x18\x05 \x01(\v2\x1e.ax_engine.v1.GenerateSamplingR\bsampling\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\"\x93\x02\n" +
	"\x10GenerateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12#\n" +
	"\rprompt_tokens\x18\x03 \x03(\rR\fpromptTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x03(\rR\foutputTokens\x12\x1f\n" +
	"\voutput_text\x18\x05 \x01(\tR\n" +
	"outputText\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rfinish_reason\x18\a \x01(\tR\ffinishReason\x12\x1d\n" +
	"\n" +
	"step_count\x18\b \x01(\x04R\tstepCount\"\xf6\x02\n" +
	"\rRequestReport\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12#\n" +
	"\rprompt_tokens\x18\x04 \x03(\rR\fpromptTokens\x126\n" +
	"\x17processed_prompt_tokens\x18\x05 \x01(\rR\x15processedPromptTokens\x12#\n" +
	"\routput_tokens\x18\x06 \x03(\rR\foutputTokens\x12\x1d\n" +
	"\n" +
	"prompt_len\x18\a \x01(\rR\tpromptLen\x12\x1d\n" +
	"\n" +
	"output_len\x18\b \x01(\rR\toutputLen\x12*\n" +
	"\x11max_output_tokens\x18\t \x01(\rR\x0fmaxOutputTokens\x12)\n" +
	"\x10cancel_requested\x18\n" +
	" \x01(\bR\x0fcancelRequested\"\xb4\x02\n" +
	"\n" +
	"StepReport\x12-\n" +
	"\x12scheduled_requests\x18\x01 \x01(\rR\x11scheduledRequests\x12)\n" +
	"\x10scheduled_tokens\x18\x02 \x01(\rR\x0fscheduledTokens\x12\x1f\n" +
	"\vttft_events\x18\x03 \x01(\rR\n" +
	"ttftEvents\x12\x1f\n" +
	"\vprefix_hits\x18\x04 \x01(\rR\n" +
	"prefixHits\x12&\n" +
	"\x0fkv_usage_blocks\x18\x05 \x01(\rR\rkvUsageBlocks\x12\x1c\n" +
	"\tevictions\x18\x06 \x01(\rR\tevictions\x12\x1e\n" +
	"\vcpu_time_us\x18\a \x01(\x04R\tcpuTimeUs\x12$\n" +
	"\x0erunner_time_us\x18\b \x01(\x04R\frunnerTimeUs\"\xba\x01\n" +
	"\x11GenerateStepEvent\x125\n" +
	"\arequest\x18\x01 \x01(\v2\x1b.ax_engine.v1.RequestReportR\arequest\x12,\n" +
	"\x04step\x18\x02 \x01(\v2\x18.ax_engine.v1.StepReportR\x04step\x12!\n" +
	"\fdelta_tokens\x18\x03 \x03(\rR\vdeltaTokens\x12\x1d\n" +
	"\n" +
	"delta_text\x18\x04 \x01(\tR\tdeltaText\"\xd3\x01\n" +
	"\x13GenerateStreamEvent\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x125\n" +
	"\arequest\x18\x02 \x01(\v2\x1b.ax_engine.v1.RequestReportR\arequest\x123\n" +
	"\x04step\x18\x03 \x01(\v2\x1f.ax_engine.v1.GenerateStepEventR\x04step\x12:\n" +
	"\bresponse\x18\x04 \x01(\v2\x1e.ax_engine.v1.GenerateResponseR\bresponse\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xcd\x01\n" +
	"\x15ChatCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x125\n" +
	"\bmessages\x18\x02 \x03(\v2\x19.ax_engine.v1.ChatMessageR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\rR\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\x04R\x04seed\x12\x12\n" +
	"\x04stop\x18\x06 \x03(\tR\x04stop\"\x81\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\rR\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\rR\vtotalTokens\"\x86\x01\n" +
	"\x14ChatCompletionChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x123\n" +
	"\amessage\x18\x02 \x01(\v2\x19.ax_engine.v1.ChatMessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\xde\x01\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12<\n" +
	"\achoices\x18\x05 \x03(\v2\".ax_engine.v1.ChatCompletionChoiceR\achoices\x12.\n" +
	"\x05usage\x18\x06 \x01(\v2\x18.ax_engine.v1.TokenUsageR\x05usage\"9\n" +
	"\tChatDelta\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x85\x01\n" +
	"\x19ChatCompletionChunkChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12-\n" +
	"\x05delta\x18\x02 \x01(\v2\x17.ax_engine.v1.ChatDeltaR\x05delta\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\xb0\x01\n" +
	"\x13ChatCompletionChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12A\n" +
	"\achoices\x18\x05 \x03(\v2'.ax_engine.v1.ChatCompletionChunkChoiceR\achoices\"\xaa\x01\n" +
	"\x11CompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\rR\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\x04R\x04seed\x12\x12\n" +
	"\x04stop\x18\x06 \x03(\tR\x04stop\"a\n" +
	"\x10CompletionChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"f\n" +
	"\x15CompletionChunkChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12#\n" +
	"\rfinish_reason\x18\x03 \x01(\tR\ffinishReason\"\xd6\x01\n" +
	"\x12CompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x128\n" +
	"\achoices\x18\x05 \x03(\v2\x1e.ax_engine.v1.CompletionChoiceR\achoices\x12.\n" +
	"\x05usage\x18\x06 \x01(\v2\x18.ax_engine.v1.TokenUsageR\x05usage\"\xa8\x01\n" +
	"\x0fCompletionChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12=\n" +
	"\achoices\x18\x05 \x03(\v2#.ax_engine.v1.CompletionChunkChoiceR\achoices\"w\n" +
	"\x11EmbeddingsRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05input\x18\x02 \x03(\rR\x05input\x12\x18\n" +
	"\apooling\x18\x03 \x01(\tR\apooling\x12\x1c\n" +
	"\tnormalize\x18\x04 \x01(\bR\tnormalize\"[\n" +
	"\rEmbeddingData\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\"X\n" +
	"\x0eEmbeddingUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\rR\fpromptTokens\x12!\n" +
	"\ftotal_tokens\x18\x02 \x01(\rR\vtotalTokens\"\xa7\x01\n" +
	"\x12EmbeddingsResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12/\n" +
	"\x04data\x18\x02 \x03(\v2\x1b.ax_engine.v1.EmbeddingDataR\x04data\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x122\n" +
	"\x05usage\x18\x04 \x01(\v2\x1c.ax_engine.v1.EmbeddingUsageR\x05usage2\xec\x05\n" +
	"\bAxEngine\x12C\n" +
	"\x06Health\x12\x1b.ax_engine.v1.HealthRequest\x1a\x1c.ax_engine.v1.HealthResponse\x12C\n" +
	"\x06Models\x12\x1b.ax_engine.v1.ModelsRequest\x1a\x1c.ax_engine.v1.ModelsResponse\x12I\n" +
	"\bGenerate\x12\x1d.ax_engine.v1.GenerateRequest\x1a\x1e.ax_engine.v1.GenerateResponse\x12T\n" +
	"\x0eStreamGenerate\x12\x1d.ax_engine.v1.GenerateRequest\x1a!.ax_engine.v1.GenerateStreamEvent0\x01\x12[\n" +
	"\x0eChatCompletion\x12#.ax_engine.v1.ChatCompletionRequest\x1a$.ax_engine.v1.ChatCompletionResponse\x12`\n" +
	"\x14StreamChatCompletion\x12#.ax_engine.v1.ChatCompletionRequest\x1a!.ax_engine.v1.ChatCompletionChunk0\x01\x12O\n" +
	"\n" +
	"Completion\x12\x1f.ax_engine.v1.CompletionRequest\x1a .ax_engine.v1.CompletionResponse\x12T\n" +
	"\x10StreamCompletion\x12\x1f.ax_engine.v1.CompletionRequest\x1a\x1d.ax_engine.v1.CompletionChunk0\x01\x12O\n" +
	"\n" +
	"Embeddings\x12\x1f.ax_engine.v1.EmbeddingsRequest\x1a .ax_engine.v1.EmbeddingsResponseB<Z:github.com/ax-engine/sdk/go/grpc/ax_engine_v1;ax_engine_v1b\x06proto3"

var (
	file_ax_engine_proto_rawDescOnce sync.Once
	file_ax_engine_proto_rawDescData []byte
)

func file_ax_engine_proto_rawDescGZIP() []byte {
	file_ax_engine_proto_rawDescOnce.Do(func() {
		file_ax_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ax_engine_proto_rawDesc), len(file_ax_engine_proto_rawDesc)))
	})
	return file_ax_engine_proto_rawDescData
}

var file_ax_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ax_engine_proto_goTypes = []any{
	(*HealthRequest)(nil),             // 0: ax_engine.v1.HealthRequest
	(*HealthResponse)(nil),            // 1: ax_engine.v1.HealthResponse
	(*ModelsRequest)(nil),             // 2: ax_engine.v1.ModelsRequest
	(*ModelCard)(nil),                 // 3: ax_engine.v1.ModelCard
	(*ModelsResponse)(nil),            // 4: ax_engine.v1.ModelsResponse
	(*GenerateSampling)(nil),          // 5: ax_engine.v1.GenerateSampling
	(*GenerateRequest)(nil),           // 6: ax_engine.v1.GenerateRequest
	(*GenerateResponse)(nil),          // 7: ax_engine.v1.GenerateResponse
	(*RequestReport)(nil),             // 8: ax_engine.v1.RequestReport
	(*StepReport)(nil),                // 9: ax_engine.v1.StepReport
	(*GenerateStepEvent)(nil),         // 10: ax_engine.v1.GenerateStepEvent
	(*GenerateStreamEvent)(nil),       // 11: ax_engine.v1.GenerateStreamEvent
	(*ChatMessage)(nil),               // 12: ax_engine.v1.ChatMessage
	(*ChatCompletionRequest)(nil),     // 13: ax_engine.v1.ChatCompletionRequest
	(*TokenUsage)(nil),                // 14: ax_engine.v1.TokenUsage
	(*ChatCompletionChoice)(nil),      // 15: ax_engine.v1.ChatCompletionChoice
	(*ChatCompletionResponse)(nil),    // 16: ax_engine.v1.ChatCompletionResponse
	(*ChatDelta)(nil),                 // 17: ax_engine.v1.ChatDelta
	(*ChatCompletionChunkChoice)(nil), // 18: ax_engine.v1.ChatCompletionChunkChoice
	(*ChatCompletionChunk)(nil),       // 19: ax_engine.v1.ChatCompletionChunk
	(*CompletionRequest)(nil),         // 20: ax_engine.v1.CompletionRequest
	(*CompletionChoice)(nil),          // 21: ax_engine.v1.CompletionChoice
	(*CompletionChunkChoice)(nil),     // 22: ax_engine.v1.CompletionChunkChoice
	(*CompletionResponse)(nil),        // 23: ax_engine.v1.CompletionResponse
	(*CompletionChunk)(nil),           // 24: ax_engine.v1.CompletionChunk
	(*EmbeddingsRequest)(nil),         // 25: ax_engine.v1.EmbeddingsRequest
	(*EmbeddingData)(nil),             // 26: ax_engine.v1.EmbeddingData
	(*EmbeddingUsage)(nil),            // 27: ax_engine.v1.EmbeddingUsage
	(*EmbeddingsResponse)(nil),        // 28: ax_engine.v1.EmbeddingsResponse
}
var file_ax_engine_proto_depIdxs = []int32{
	3,  // 0: ax_engine.v1.ModelsResponse.data:type_name -> ax_engine.v1.ModelCard
	5,  // 1: ax_engine.v1.GenerateRequest.sampling:type_name -> ax_engine.v1.GenerateSampling
	8,  // 2: ax_engine.v1.GenerateStepEvent.request:type_name -> ax_engine.v1.RequestReport
	9,  // 3: ax_engine.v1.GenerateStepEvent.step:type_name -> ax_engine.v1.StepReport
	8,  // 4: ax_engine.v1.GenerateStreamEvent.request:type_name -> ax_engine.v1.RequestReport
	10, // 5: ax_engine.v1.GenerateStreamEvent.step:type_name -> ax_engine.v1.GenerateStepEvent
	7,  // 6: ax_engine.v1.GenerateStreamEvent.response:type_name -> ax_engine.v1.GenerateResponse
	12, // 7: ax_engine.v1.ChatCompletionRequest.messages:type_name -> ax_engine.v1.ChatMessage
	12, // 8: ax_engine.v1.ChatCompletionChoice.message:type_name -> ax_engine.v1.ChatMessage
	15, // 9: ax_engine.v1.ChatCompletionResponse.choices:type_name -> ax_engine.v1.ChatCompletionChoice
	14, // 10: ax_engine.v1.ChatCompletionResponse.usage:type_name -> ax_engine.v1.TokenUsage
	17, // 11: ax_engine.v1.ChatCompletionChunkChoice.delta:type_name -> ax_engine.v1.ChatDelta
	18, // 12: ax_engine.v1.ChatCompletionChunk.choices:type_name -> ax_engine.v1.ChatCompletionChunkChoice
	21, // 13: ax_engine.v1.CompletionResponse.choices:type_name -> ax_engine.v1.CompletionChoice
	14, // 14: ax_engine.v1.CompletionResponse.usage:type_name -> ax_engine.v1.TokenUsage
	22, // 15: ax_engine.v1.CompletionChunk.choices:type_name -> ax_engine.v1.CompletionChunkChoice
	26, // 16: ax_engine.v1.EmbeddingsResponse.data:type_name -> ax_engine.v1.EmbeddingData
	27, // 17: ax_engine.v1.EmbeddingsResponse.usage:type_name -> ax_engine.v1.EmbeddingUsage
	0,  // 18: ax_engine.v1.AxEngine.Health:input_type -> ax_engine.v1.HealthRequest
	2,  // 19: ax_engine.v1.AxEngine.Models:input_type -> ax_engine.v1.ModelsRequest
	6,  // 20: ax_engine.v1.AxEngine.Generate:input_type -> ax_engine.v1.GenerateRequest
	6,  // 21: ax_engine.v1.AxEngine.StreamGenerate:input_type -> ax_engine.v1.GenerateRequest
	13, // 22: ax_engine.v1.AxEngine.ChatCompletion:input_type -> ax_engine.v1.ChatCompletionRequest
	13, // 23: ax_engine.v1.AxEngine.StreamChatCompletion:input_type -> ax_engine.v1.ChatCompletionRequest
	20, // 24: ax_engine.v1.AxEngine.Completion:input_type -> ax_engine.v1.CompletionRequest
	20, // 25: ax_engine.v1.AxEngine.StreamCompletion:input_type -> ax_engine.v1.CompletionRequest
	25, // 26: ax_engine.v1.AxEngine.Embeddings:input_type -> ax_engine.v1.EmbeddingsRequest
	1,  // 27: ax_engine.v1.AxEngine.Health:output_type -> ax_engine.v1.HealthResponse
	4,  // 28: ax_engine.v1.AxEngine.Models:output_type -> ax_engine.v1.ModelsResponse
	7,  // 29: ax_engine.v1.AxEngine.Generate:output_type -> ax_engine.v1.GenerateResponse
	11, // 30: ax_engine.v1.AxEngine.StreamGenerate:output_type -> ax_engine.v1.GenerateStreamEvent
	16, // 31: ax_engine.v1.AxEngine.ChatCompletion:output_type -> ax_engine.v1.ChatCompletionResponse
	19, // 32: ax_engine.v1.AxEngine.StreamChatCompletion:output_type -> ax_engine.v1.ChatCompletionChunk
	23, // 33: ax_engine.v1.AxEngine.Completion:output_type -> ax_engine.v1.CompletionResponse
	24, // 34: ax_engine.v1.AxEngine.StreamCompletion:output_type -> ax_engine.v1.CompletionChunk
	28, // 35: ax_engine.v1.AxEngine.Embeddings:output_type -> ax_engine.v1.EmbeddingsResponse
	27, // [27:36] is the sub-list for method output_type
	18, // [18:27] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_ax_engine_proto_init() }
func file_ax_engine_proto_init() {
	if File_ax_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ax_engine_proto_rawDesc), len(file_ax_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ax_engine_proto_goTypes,
		DependencyIndexes: file_ax_engine_proto_depIdxs,
		MessageInfos:      file_ax_engine_proto_msgTypes,
	}.Build()
	File_ax_engine_proto = out.File
	file_ax_engine_proto_goTypes = nil
	file_ax_engine_proto_depIdxs = nil
}
