// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: ax_engine.proto

package ax_engine_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AxEngine_Health_FullMethodName               = "/ax_engine.v1.AxEngine/Health"
	AxEngine_Models_FullMethodName               = "/ax_engine.v1.AxEngine/Models"
	AxEngine_Generate_FullMethodName             = "/ax_engine.v1.AxEngine/Generate"
	AxEngine_StreamGenerate_FullMethodName       = "/ax_engine.v1.AxEngine/StreamGenerate"
	AxEngine_ChatCompletion_FullMethodName       = "/ax_engine.v1.AxEngine/ChatCompletion"
	AxEngine_StreamChatCompletion_FullMethodName = "/ax_engine.v1.AxEngine/StreamChatCompletion"
	AxEngine_Completion_FullMethodName           = "/ax_engine.v1.AxEngine/Completion"
	AxEngine_StreamCompletion_FullMethodName     = "/ax_engine.v1.AxEngine/StreamCompletion"
	AxEngine_Embeddings_FullMethodName           = "/ax_engine.v1.AxEngine/Embeddings"
)

// AxEngineClient is the client API for AxEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AxEngineClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Models(ctx context.Context, in *ModelsRequest, opts ...grpc.CallOption) (*ModelsResponse, error)
	// Native generate: unary and server-streaming
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	StreamGenerate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateStreamEvent], error)
	// OpenAI-compatible chat: unary and server-streaming
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	StreamChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionChunk], error)
	// OpenAI-compatible text completion: unary and server-streaming
	Completion(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
	StreamCompletion(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompletionChunk], error)
	// Embeddings (unary only)
	Embeddings(ctx context.Context, in *EmbeddingsRequest, opts ...grpc.CallOption) (*EmbeddingsResponse, error)
}

type axEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAxEngineClient(cc grpc.ClientConnInterface) AxEngineClient {
	return &axEngineClient{cc}
}

func (c *axEngineClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AxEngine_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *axEngineClient) Models(ctx context.Context, in *ModelsRequest, opts ...grpc.CallOption) (*ModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelsResponse)
	err := c.cc.Invoke(ctx, AxEngine_Models_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *axEngineClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, AxEngine_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *axEngineClient) StreamGenerate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateStreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AxEngine_ServiceDesc.Streams[0], AxEngine_StreamGenerate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateStreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxEngine_StreamGenerateClient = grpc.ServerStreamingClient[GenerateStreamEvent]

func (c *axEngineClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, AxEngine_ChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *axEngineClient) StreamChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatCompletionChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AxEngine_ServiceDesc.Streams[1], AxEngine_StreamChatCompletion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatCompletionRequest, ChatCompletionChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxEngine_StreamChatCompletionClient = grpc.ServerStreamingClient[ChatCompletionChunk]

func (c *axEngineClient) Completion(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, AxEngine_Completion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *axEngineClient) StreamCompletion(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CompletionChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AxEngine_ServiceDesc.Streams[2], AxEngine_StreamCompletion_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompletionRequest, CompletionChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxEngine_StreamCompletionClient = grpc.ServerStreamingClient[CompletionChunk]

func (c *axEngineClient) Embeddings(ctx context.Context, in *EmbeddingsRequest, opts ...grpc.CallOption) (*EmbeddingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbeddingsResponse)
	err := c.cc.Invoke(ctx, AxEngine_Embeddings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AxEngineServer is the server API for AxEngine service.
// All implementations must embed UnimplementedAxEngineServer
// for forward compatibility.
type AxEngineServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Models(context.Context, *ModelsRequest) (*ModelsResponse, error)
	// Native generate: unary and server-streaming
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	StreamGenerate(*GenerateRequest, grpc.ServerStreamingServer[GenerateStreamEvent]) error
	// OpenAI-compatible chat: unary and server-streaming
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	StreamChatCompletion(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionChunk]) error
	// OpenAI-compatible text completion: unary and server-streaming
	Completion(context.Context, *CompletionRequest) (*CompletionResponse, error)
	StreamCompletion(*CompletionRequest, grpc.ServerStreamingServer[CompletionChunk]) error
	// Embeddings (unary only)
	Embeddings(context.Context, *EmbeddingsRequest) (*EmbeddingsResponse, error)
	mustEmbedUnimplementedAxEngineServer()
}

// UnimplementedAxEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAxEngineServer struct{}

func (UnimplementedAxEngineServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAxEngineServer) Models(context.Context, *ModelsRequest) (*ModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Models not implemented")
}
func (UnimplementedAxEngineServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedAxEngineServer) StreamGenerate(*GenerateRequest, grpc.ServerStreamingServer[GenerateStreamEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamGenerate not implemented")
}
func (UnimplementedAxEngineServer) ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedAxEngineServer) StreamChatCompletion(*ChatCompletionRequest, grpc.ServerStreamingServer[ChatCompletionChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamChatCompletion not implemented")
}
func (UnimplementedAxEngineServer) Completion(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Completion not implemented")
}
func (UnimplementedAxEngineServer) StreamCompletion(*CompletionRequest, grpc.ServerStreamingServer[CompletionChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamCompletion not implemented")
}
func (UnimplementedAxEngineServer) Embeddings(context.Context, *EmbeddingsRequest) (*EmbeddingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embeddings not implemented")
}
func (UnimplementedAxEngineServer) mustEmbedUnimplementedAxEngineServer() {}
func (UnimplementedAxEngineServer) testEmbeddedByValue()                  {}

// UnsafeAxEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AxEngineServer will
// result in compilation errors.
type UnsafeAxEngineServer interface {
	mustEmbedUnimplementedAxEngineServer()
}

func RegisterAxEngineServer(s grpc.ServiceRegistrar, srv AxEngineServer) {
	// If the following call panics, it indicates UnimplementedAxEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AxEngine_ServiceDesc, srv)
}

func _AxEngine_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxEngineServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AxEngine_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxEngineServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AxEngine_Models_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxEngineServer).Models(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AxEngine_Models_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxEngineServer).Models(ctx, req.(*ModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AxEngine_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxEngineServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AxEngine_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxEngineServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AxEngine_StreamGenerate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AxEngineServer).StreamGenerate(m, &grpc.GenericServerStream[GenerateRequest, GenerateStreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxEngine_StreamGenerateServer = grpc.ServerStreamingServer[GenerateStreamEvent]

func _AxEngine_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxEngineServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AxEngine_ChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxEngineServer).ChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AxEngine_StreamChatCompletion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AxEngineServer).StreamChatCompletion(m, &grpc.GenericServerStream[ChatCompletionRequest, ChatCompletionChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxEngine_StreamChatCompletionServer = grpc.ServerStreamingServer[ChatCompletionChunk]

func _AxEngine_Completion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxEngineServer).Completion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AxEngine_Completion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxEngineServer).Completion(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AxEngine_StreamCompletion_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AxEngineServer).StreamCompletion(m, &grpc.GenericServerStream[CompletionRequest, CompletionChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AxEngine_StreamCompletionServer = grpc.ServerStreamingServer[CompletionChunk]

func _AxEngine_Embeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AxEngineServer).Embeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AxEngine_Embeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AxEngineServer).Embeddings(ctx, req.(*EmbeddingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AxEngine_ServiceDesc is the grpc.ServiceDesc for AxEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AxEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ax_engine.v1.AxEngine",
	HandlerType: (*AxEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _AxEngine_Health_Handler,
		},
		{
			MethodName: "Models",
			Handler:    _AxEngine_Models_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _AxEngine_Generate_Handler,
		},
		{
			MethodName: "ChatCompletion",
			Handler:    _AxEngine_ChatCompletion_Handler,
		},
		{
			MethodName: "Completion",
			Handler:    _AxEngine_Completion_Handler,
		},
		{
			MethodName: "Embeddings",
			Handler:    _AxEngine_Embeddings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGenerate",
			Handler:       _AxEngine_StreamGenerate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamChatCompletion",
			Handler:       _AxEngine_StreamChatCompletion_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCompletion",
			Handler:       _AxEngine_StreamCompletion_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ax_engine.proto",
}
