from collections.abc import Iterator
from typing import Self


class TextStream(Iterator[str]):
    def __iter__(self) -> Self: ...
    def __next__(self) -> str: ...


class Session:
    @property
    def context_length(self) -> int: ...
    @property
    def position(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    def generate(
        self,
        prompt: str,
        *,
        max_tokens: int = 128,
        temperature: float = 0.8,
        top_k: int = 40,
        top_p: float = 0.9,
        min_p: float = 0.0,
        repeat_penalty: float = 1.0,
        stop: list[str] | None = None,
        seed: int | None = None,
    ) -> str: ...
    def stream(
        self,
        prompt: str,
        *,
        max_tokens: int = 128,
        temperature: float = 0.8,
        top_k: int = 40,
        top_p: float = 0.9,
        min_p: float = 0.0,
        repeat_penalty: float = 1.0,
        stop: list[str] | None = None,
        seed: int | None = None,
    ) -> TextStream: ...
    def chat(
        self,
        messages: list[dict[str, str]],
        *,
        max_tokens: int = 128,
        temperature: float = 0.8,
        top_k: int = 40,
        top_p: float = 0.9,
        min_p: float = 0.0,
        repeat_penalty: float = 1.0,
        stop: list[str] | None = None,
        seed: int | None = None,
    ) -> str: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object | None, exc: object | None, traceback: object | None) -> None: ...


class Model:
    @staticmethod
    def load(path: str, backend: str | None = None) -> Model: ...
    @property
    def architecture(self) -> str: ...
    @property
    def context_length(self) -> int: ...
    @property
    def vocab_size(self) -> int: ...
    @property
    def bos_token_id(self) -> int: ...
    @property
    def eos_token_id(self) -> int: ...
    @property
    def model_name(self) -> str | None: ...
    @property
    def support_note(self) -> str | None: ...
    @property
    def closed(self) -> bool: ...
    def tokenize(self, text: str, add_special: bool = False) -> list[int]: ...
    def decode(self, token_ids: list[int]) -> str: ...
    def session(self, ctx_size: int | None = None, seed: int | None = None) -> Session: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object | None, exc: object | None, traceback: object | None) -> None: ...
